# You can override the included template(s) by including variable overrides
#
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
#
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
#
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

default:
  image: ruby:3.3.4
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby

stages:
  - setup
  - build
  - test
  - deploy

.setup_node: &setup_node
  - apt-get install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
  - bash nodesource_setup.sh
  - apt-get install -y nodejs
  - npm install --global yarn

.install_deps: &install_deps
  # Ruby deps
  - bundle config set --local path 'vendor/ruby'
  - bundle install -j $(nproc)
  # Node deps
  - yarn install --frozen-lockfile --no-progress

.setup_languages: &setup_languages
  - *setup_node
  - *install_deps

test-langs:
  stage: setup
  script:
    - *setup_languages

.brakeman-scan:
  stage: test
  script:
  - echo "Brakeman scan..."
  - echo "Scan complete."
.bundle-audit:
  stage: build
  script:
  - echo "Bundle audit..."
  - echo "Scan complete"
.yarn-audit:
  stage: build
  script: 
  - echo "Yarn audit..."
  - echo "Scan complete"
.ruby-bom:
  stage: build
  script:
  - echo "Ruby SBOM Generation..."
  - echo "Generation Complete"
.owasp-scan:
  stage: test
  #TODO: check gitlab security templates for this scan
  #TODO: Owasp Dail Scan
  script:
  - echo "OWASP ZAP Scan..."
  - echo "Scan Complete"
.pa11y-scan:
  stage: test
  script:
  - echo "Pa11y Scan..."
  - echo "Scan Complete"
.rspec:
  stage: test
  script:
  - echo "Rspec..."
  - echo "Rspec Complete"

.unit-test-job:
  stage: test
  script:
  - echo "Running unit tests... This will take about 60 seconds."
  - sleep 60
  - echo "Code coverage is 90%"
.lint-test-job:
  stage: test
  script:
  - echo "Linting code... This will take about 10 seconds."
  - sleep 10
  - echo "No lint issues found."
.deploy-job:
  environment: production
  stage: deploy
  script:
  - echo "Deploying application..."
  - echo "Application successfully deployed."
.sast:
  stage: test
  include:
  - template: Security/SAST.gitlab-ci.yml
